### ISSUE TITLE
مشکل در نصب

### ISSUE THREAD

**Issue by jpro123** [mastani/laravel-idpay#2]
./composer.json has been updated
Running composer update mastani/laravel-idpay
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mastani/laravel-idpay dev-master -> satisfiable by mastani/laravel-idpay[dev-master].
    - mastani/laravel-idpay dev-master requires illuminate/contracts 5.* -> found illuminate/contracts[v5.0.0, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^8.83).

You can also try re-running composer require with an explicit version constraint, e.g. "composer require mastani/laravel-idpay:*" to figure out if any version is installable, or "composer require mastani/laravel-idpay:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

لاراول 8 استفاده می کنم . 
contracts  هم که ارور میده نصب کردم ولی باز رفع نشد . 
پکیج هایی هم که کنتراکت احتیاج داره هم نصب کردم ولی باز نصب نشد

**Comment by mastani** [comment]
Thanks for your feedback and sorry for late reply. I updated the dependencies, Shouldn't be a problem anymore.
